stages:
  - test

image: python:3.12.0-slim

test:
  stage: test
  services:
    - mariadb:latest
  before_script:
    - >
      apt update &&
      apt install -y --no-install-recommends
      gcc
      libmariadb-dev
      mariadb-client
    - python --version; pip --version
    - pip install --no-cache-dir -r requirements.txt
  script: bash test.sh
