stages:
  - test

image: python:3.12.0-slim

test:
  stage: test
  variables:
    MARIADB_ROOT_PASSWORD: "root"
    MARIADB_HOST: "mariadb"
    MARIADB_DATABASE: "test_fruits"
  services:
    - mariadb:latest
  before_script:
    - >
      apt update &&
      apt install -y --no-install-recommends
      gcc
      libmariadb-dev
      mariadb-client
    - >
      mariadb
      --user=root
      --password=$MARIADB_ROOT_PASSWORD
      --host=$MARIADB_HOST
      -e "create database IF NOT EXISTS $MARIADB_DATABASE;
          use $MARIADB_DATABASE;"
    - python --version; pip --version
    - pip install --no-cache-dir -r requirements.txt
  script: bash test.sh
