stages:
  - test

image: python:3.12.0-slim

lint-test:
  stage: test
  script:
    - pip install Flake8-pyproject
    - flake8 ./src ./test 
  allow_failure: true

type-test:
  stage: test
  before_script:
    - >
      apt update &&
      apt install -y --no-install-recommends
      gcc
      libmariadb-dev
      mariadb-client
    - pip install --no-cache-dir -r requirements.txt
  script:
    - pip install mypy pytest
    - mypy ./src ./test

unit-test:
  stage: test
  variables:
    MARIADB_ROOT_PASSWORD: "root"
    MARIADB_HOST: "mariadb"
    MARIADB_DATABASE: "test_fruits"
  services:
    - mariadb:latest
  before_script:
    - >
      apt update &&
      apt install -y --no-install-recommends
      gcc
      libmariadb-dev
      mariadb-client
    - >
      mariadb
      --user=root
      --password=$MARIADB_ROOT_PASSWORD
      --host=$MARIADB_HOST
      -e "create database IF NOT EXISTS $MARIADB_DATABASE;
          create database IF NOT EXISTS test_cofre;
          create database IF NOT EXISTS test_cofre_empty;"
    - pip install --no-cache-dir -r requirements.txt
  script:
    - pip install --no-cache-dir -r test-requirements.txt
    - coverage run
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 10 days 
