stages:
  - test

image: python:3.12.0-slim

before_script:
  - python --version; pip --version
  - apt update && apt install gcc libmariadb-dev -y
  - pip install --no-cache-dir -r requirements.txt

test:
  stage: test
  script: bash test.sh
