---
repos:
  - repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
        args: ["--max-complexity=10"]
