python -m mypy  ^
    .\src\mariadb\__init__.pyi ^
    .\src\mariadb\connections.pyi ^
    .\src\mariadb\cursors.pyi ^
    .\src\mariadb\constants\__init__.pyi ^
    .\src\mariadb\constants\FIELD_FLAG.pyi ^
    .\src\mariadb\constants\FIELD_TYPE.pyi ^
    .\src\flask_swagger.pyi ^
    .\src\flask_swagger_ui.pyi ^
    .\src\admin.py ^
    .\src\cofre.py ^
    .\src\validator.py ^
    .\src\decorators\__init__.py ^
    .\src\decorators\for_all.py ^
    .\src\decorators\single.py ^
    .\src\decorators\tracer.py ^
    .\src\connection\__init__.py ^
    .\src\connection\conn.py ^
    .\src\connection\sqlfactory.py ^
    .\src\connection\mysqlconn.py ^
    .\src\connection\mariadbconn.py ^
    .\src\connection\sqlite3conn.py ^
    .\src\cofre_de_senhas\__init__.py ^
    .\src\cofre_de_senhas\erro.py ^
    .\src\cofre_de_senhas\dao.py ^
    .\src\cofre_de_senhas\service.py ^
    .\src\cofre_de_senhas\service_impl.py ^
    .\src\cofre_de_senhas\httpwrap.py ^
    .\src\cofre_de_senhas\controller.py ^
    .\src\cofre_de_senhas\bd\__init__.py ^
    .\src\cofre_de_senhas\bd\raiz.py ^
    .\src\cofre_de_senhas\bd\bd_dao_impl.py ^
    .\src\cofre_de_senhas\usuario\__init__.py ^
    .\src\cofre_de_senhas\usuario\usuario.py ^
    .\src\cofre_de_senhas\usuario\usuario_dao_impl.py ^
    .\src\cofre_de_senhas\categoria\__init__.py ^
    .\src\cofre_de_senhas\categoria\categoria.py ^
    .\src\cofre_de_senhas\categoria\categoria_dao_impl.py ^
    .\src\cofre_de_senhas\segredo\__init__.py ^
    .\src\cofre_de_senhas\segredo\segredo.py ^
    .\src\cofre_de_senhas\segredo\segredo_dao_impl.py