pip install mypy                   --require-virtualenv --timeout 8
pip install pytest                 --require-virtualenv --timeout 8
pip install dacite                 --require-virtualenv --timeout 8
pip install mariadb                --require-virtualenv --timeout 8
pip install mysql-connector-python --require-virtualenv --timeout 8
pip install requests               --require-virtualenv --timeout 8
pip install types-requests         --require-virtualenv --timeout 8
pip install flask                  --require-virtualenv --timeout 8
pip install radon                  --require-virtualenv --timeout 8
pip install coverage               --require-virtualenv --timeout 8